name: ncov-phylogeography
channels:
  - conda-forge
  - bioconda
  - anaconda
  - defaults
dependencies:
  # Snakemake Execution
  - bioconda::snakemake  
  - conda-forge::python<3.10
  - conda-forge::pip
  - conda-forge::sqlite
  # Metadata
  - conda-forge::geopy=2.0.0
  # Alignment
  - bioconda:snippy=4.6.0
  - bioconda:vt=0.57721
  - bioconda:snp-dists=0.7.0
  # Phylogeny
  - bioconda::iqtree
  # Auspice Visualization
  - click
  - augur=10.3.0
  - nodejs=13.13.0
  
  - pip:
    - ncbimeta==0.8.2

# npm:
# - auspice@2.32.1
