#------------------------------------------------------------------------------#
# Generic config
#------------------------------------------------------------------------------#
restart-times: 0
max-jobs-per-second: 1
latency-wait: 5
keep-going: False
rerun-incomplete:  True
printshellcmds: True

#------------------------------------------------------------------------------#
# System config
#------------------------------------------------------------------------------#
# Total resources for the entire workflow
# ex. 4 cpus, 2GB each (total 8GB)
resources: [cpus=2, mem_mb=12000, load=100]
# Default resources for a job
default-resources: [cpus=1, mem_mb=4000, time_min=60]
# Maximum number of jobs to run
jobs : "2"
